### ISSUE TITLE
Normal mapping

### ISSUE THREAD

**Issue by HolgerW1** [stuartcaunt/isgl3d#21]
Support normal mapping

**Comment by HolgerW1** [comment]
Custom shader demo already integrated, full integration into isgl3d not yet done

**Comment by codetiger** [comment]
Am working on adding Normal mapping to any texture. Am adding another method in TextureMaterial class to add normal maps and send the map to generic shader. Let me know if this way is correct.

**Comment by codetiger** [comment]
Hi, I just gave a pull request with changes for adding Normal Mapping as basic support.

**Comment by HolgerW1** [comment]
Good job! Merged and issue closed.
