### ISSUE TITLE
Ability to disable POD Importer logging

### ISSUE THREAD

**Issue by ghost** [stuartcaunt/isgl3d#26]
Can implement this, but not sure about the proper way. Thinking of something like 
# define Suppress_POD_importer_logs

What do you think?

**Comment by HolgerW1** [comment]
Regarding the pod importer: this class only prints the details to the log if you call the printPODInfo method. So I'm not 100% sure I understand what you mean.

If you're looking for a simple way to call this method in debug mode and suppress in release compilations then an easy way to do this would be via:

#if DEBUG = 1
  [podImporter printPODInfo];
#endif

Generally spoken: there's currently no possibility in isgl3d to configure the verbosity of the logs but I think a general solution would be useful. I'll add this to the todo list for v1.3.0

**Comment by ghost** [comment]
I am talking about calls like for example in addMeshesToScene method there is a line 

NSLog(@"Adding node: %s:", nodeInfo.pszName);

that is called for each node, and log usually contains a long list of nodes that were added.

**Comment by HolgerW1** [comment]
Ah ok, that issue will be solved with #27

**Comment by HolgerW1** [comment]
Fixed with latest branch
