### ISSUE TITLE
Ability to disable bone meshes

### ISSUE THREAD

**Issue by ghost** [stuartcaunt/isgl3d#37]
Currently all bones have assigned to them meshes (for debugging purpose I guess), and the only way to disable them is to change the library code at the place where they are created.

**Comment by graylikeme** [comment]
You can disable bone meshes. How do you load your model?

**Comment by ghost** [comment]
Yep, found that not so far ago and forgot I opened the issue, thanks for the comment. At first I thought that you need both - animated meshes and bones added to the skeleton. Closing the issue now.
