### ISSUE TITLE
Renderer chokes on high vertex count scenes

### ISSUE THREAD

**Issue by DavidYKay** [stuartcaunt/isgl3d#7]
I've encountered what appears to be a bug in the renderer.

By  creating an Icosphere in blender and subdividing the surfaces, I've found that somewhere between 21,000 and 21,600 faces, the sphere fails to render properly. I don't know the proper term for the problem, but it seems that some vertices don't make it into the mesh, and so the triangles now render between the wrong vertices.

Here's an [image](http://i.imgur.com/WFXv5.png) of the problem. This is using `Isgl3dPODImporter` to import the POD model.

Likewise if I create a sphere in code, using `Isgl3dSphere` I get a similar result: [image](http://i.imgur.com/1LGW6.png).

I'm a 3D noob, so let me know if I'm missing something.

Thanks!

**Comment by HolgerW1** [comment]
How do you import your blender model, via POD file?
If so, did you check if PVRShaman is able to load and render your POD file properly?

**Comment by DavidYKay** [comment]
Yep. Importing via POD.

Will throw it into PVRShaman and update you.

Thanks!

**Comment by DavidYKay** [comment]
So far, it seems that iSGL3D mirrors the behavior of PVRShaman! 

Closing. Will re-open if I find this is not actually the case.
